### PR TITLE
More UI improvements and better dev mode

### LINKED ISSUE #37: hover and focus styles for icons
'go-to-trace' and 'accordion' buttons don't have hover/focus styles

### PR DESCRIPTION
**Pull request by typeholes**
fixes #37 

grid like layout for trace lines

somewhat reactive to page width, but still scrolls when too narrow.  

srcDev package launches a bridge between the extension and ui:dev so you get bidirectional communication instead of the fixed commands/responses we had before

### CODE REVIEW

**Comment by typeholes** [comment]
If you think the UI is up to par, please move the UI commands out of experimental

**Comment by typeholes** [comment]
Something seems off with the tree nesting in more complicated repos, investigating ...

**Comment by typeholes** [comment]
I've verified that the data is correct.  It looks like a reactive effect isn't getting triggered consistently.

**Comment by typeholes** [comment]
fixed reactivity and listener issues.  performance is much better now as well.  
sorting no longer triggers a fetch of the nodes.  Will undraft after a test pass

**Comment by typeholes** [comment]
one last bug to fix in the morning: trace file names get duplicated in the UI when switching projects - need to move listener and state to appState.ts

**Review by danielroe — APPROVED** [review]

**Comment by danielroe** [comment]
Looking good! A couple of comments.

- click targets should be bigger on the expand/goto buttons
- I think there's something wrong with the relative path that's being printed - it should be something like `index.ts` rather than `../../../../../../users/daniel/code/tsperf/tracer/playground/index.ts`
- 'go to trace' still doesn't seem to work with split screen view
- if I run 'tsc trace' and then open the viewer I don't see anything - nothing appears to have happened... - it only seems to work if the viewer is open and then I run 'tsc trace'

https://github.com/tsperf/tracer/assets/28706372/f48b41d6-191e-4e6a-8aae-b89b5a890748

**Pull request merged**
